### PR TITLE
Add support of special symbols in user/password uri components.

### PR DESCRIPTION
**Pull request by simbadltd**
- It is impossible to have RMQ user with password contained special symbols (e.g. P@ssw0rd)

### CODE REVIEW

**Comment by simbadltd** [comment]
Hi @LordMike. Thanks for your tool! I've decided to support one more life use-case :)

**Comment by LordMike** [comment]
So, if you were to use `%40` for `@`, it fails?

If so, we definitely need to decode the value.. :|

**Comment by simbadltd** [comment]
Yes, it fails with:

Unhandled Exception: RabbitMQ.Client.Exceptions.BrokerUnreachableException: None of the specified endpoints were reachable ---> RabbitMQ.Client.Exceptions.AuthenticationFailureException: ACCESS_REFUSED - Login was refused using authentication mechanism PLAI
N. For details see the broker logfile.
   at RabbitMQ.Client.Framing.Impl.Connection.StartAndTune()
   at RabbitMQ.Client.Framing.Impl.Connection.Open(Boolean insist)
   at RabbitMQ.Client.Framing.Impl.AutorecoveringConnection.Init(IFrameHandler fh)
   at RabbitMQ.Client.ConnectionFactory.CreateConnection(IEndpointResolver endpointResolver, String clientProvidedName)
   
Because Uri returns `UserInfo` as is (without decoding). That's why we need to decode it manually.

**Comment by LordMike** [comment]
Was looking into it - I suppose `Uri.UnescapeDataString` is ok.

**Pull request merged**
